### ISSUE TITLE
Show podcast file in template

### ISSUE THREAD

**Issue by rocchidavide** [stefansl/news_podcasts#2]
Hi, first of all thank you for this extension.
I'm trying to show the podcast file in my news_full.html5 template, but what i have in $this->podcast is

``` php
[podcast] => Æ`Ú»:äŠL
```

How can I get my file so I can style it?

**Comment by rocchidavide** [comment]
Ok, i found:

``` php
$objFile = FilesModel::findByUuid($this->podcast);
```

I don't know but before syncronizing manually files in file manager, it didn't work

**Comment by stefansl** [comment]
Hi, the plan is to create a module for that see #1
